### ISSUE TITLE
Open table (name contane space) bring error

### ISSUE THREAD

**Issue by glushko311** [fastflo/emma#3]
Environment:
OS: Ubuntu 14.04
Emma 0.7

Steps to reproduce:
1.Create a table name contane space
2.Choice creating table

![default](https://cloud.githubusercontent.com/assets/10559084/6833742/f18b7774-d337-11e4-949d-6d4cba6e7eaa.png)

**Comment by fastflo** [comment]
should be fixed in current head. there was a select query with unquoted table name in the query string.
