### ISSUE TITLE
Function "Truncate" isn't working

### ISSUE THREAD

**Issue by glushko311** [fastflo/emma#4]
Environment:
OS: Ubuntu 14.04
Emma 0.7

Steps to reproduce:

1.Choice a table 
2.Click the button "Truncate"
3. Click "Yes"
![truncate_isnt_working1](https://cloud.githubusercontent.com/assets/10559084/6847398/0a9c319e-d3cf-11e4-8b9f-ffcd54d8d313.png)
![truncate_isnt_working](https://cloud.githubusercontent.com/assets/10559084/6847392/f865c95e-d3ce-11e4-8423-135dc6159ff4.png)

**Comment by MrElectroNick** [comment]
not a bug actually
